spring:
  application:
    name: notification-service
  data:
    mongodb:
      auto-index-creation: true
  kafka:
    consumer:
      group-id: notifications-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.*"
  lifecycle:
    timeout-per-shutdown-phase: 30s

swagger:
  config: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8082
  shutdown: graceful