spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DeduplicateResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
api-gateway:
  depends_on:
    user-service:
      condition: service_healthy
server:
  shutdown: graceful