spring:
  application:
    name: user-service
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 10
      acks: all
      properties:
        delivery.timeout.ms: 120000
        retry.backoff.ms: 100
        enable.idempotence: true
swagger:
  config: true



management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8081
  shutdown: graceful