spring:
  application:
    name: event-service
  cache:
    type: redis
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
  jpa:
    hibernate:
      ddl-auto: none
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 10
      acks: all
      properties:
        delivery.timeout.ms: 120000
        retry.backoff.ms: 100
        enable.idempotence: true
    consumer:
      group-id: events-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "org.example.*"
  lifecycle:
    timeout-per-shutdown-phase: 30s

swagger:
  config: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8083
  shutdown: graceful